# Generated by Django 4.0.6 on 2022-08-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_alter_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserName',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
