# Generated by Django 4.0.6 on 2022-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='EndDate',
            field=models.DateField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='StartDate',
            field=models.DateField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='EndDate',
            field=models.DateField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='StartDate',
            field=models.DateField(auto_created=True, blank=True),
        ),
    ]
