# Generated by Django 4.0.6 on 2022-08-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_alter_education_enddate_alter_education_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[(30, 'beginner'), (60, 'intermediate'), (100, 'advance')], max_length=10),
        ),
    ]
